/**
 * Termyte OpenCode Plugin
 *
 * This plugin forwards OpenCode events to the `termyte hook` CLI,
 * which persists observations, extracts memories, and updates
 * confidence scores.
 *
 * Auto-generated by `termyte plugin install`. Do not edit by hand
 * unless you know what you are doing.
 */
import { spawn } from "node:child_process";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";

const TERMYTE_PATHS = [
  process.env.TERMYTE_BIN,
  join(homedir(), ".npm-global", "bin", "termyte"),
  join(homedir(), ".local", "bin", "termyte"),
  "/usr/local/bin/termyte",
  "termyte",
].filter(Boolean) as string[];

function findTermyteBinary(): string {
  for (const p of TERMYTE_PATHS) {
    if (p === "termyte") return p;
    if (existsSync(p)) return p;
  }
  return "termyte";
}

function callTermyteHook(payload: Record<string, unknown>): void {
  const bin = findTermyteBinary();
  try {
    const child = spawn(bin, ["hook"], {
      stdio: ["pipe", "ignore", "ignore"],
      detached: true,
      shell: false,
    });
    child.stdin?.write(JSON.stringify(payload));
    child.stdin?.end();
    child.unref();
  } catch {
    // Never let plugin errors break the agent.
  }
}

function safeString(v: unknown): string | undefined {
  return typeof v === "string" ? v : undefined;
}

export const TermytePlugin = async ({
  project,
  directory,
}: {
  project: { id?: string; worktree?: string };
  directory: string;
}) => {
  const sessionId = project?.id ?? `oc-${Date.now()}`;
  const cwd = directory ?? project?.worktree ?? process.cwd();

  return {
    "session.created": async () => {
      callTermyteHook({
        platform: "opencode",
        event: "session.created",
        sessionId,
        cwd,
        sessionSource: "startup",
      });
    },

    "session.idle": async () => {
      callTermyteHook({
        platform: "opencode",
        event: "session.idle",
        sessionId,
        cwd,
        sessionSource: "clear",
      });
    },

    "session.error": async (_input: unknown, _output: unknown) => {
      callTermyteHook({
        platform: "opencode",
        event: "session.error",
        sessionId,
        cwd,
        sessionSource: "clear",
      });
    },

    "message.part.updated": async (input: any) => {
      const part = input?.part;
      if (!part) return;

      if (part.type === "text") {
        const text = safeString(part.text);
        if (!text) return;
        const role = part.role ?? "assistant";
        if (role === "user") {
          callTermyteHook({
            platform: "opencode",
            event: "message.part.updated",
            sessionId,
            cwd,
            prompt: text,
            part: { type: "text", role: "user", text },
            turnId: input?.messageID ?? input?.partID,
          });
        } else {
          callTermyteHook({
            platform: "opencode",
            event: "message.part.updated",
            sessionId,
            cwd,
            lastAssistantMessage: text,
            part: { type: "text", role: "assistant", text },
            turnId: input?.messageID ?? input?.partID,
          });
        }
        return;
      }

      if (part.type === "tool" || part.type === "tool_use") {
        callTermyteHook({
          platform: "opencode",
          event: "message.part.updated",
          sessionId,
          cwd,
          part,
          turnId: input?.messageID ?? input?.partID,
        });
      }
    },

    "tool.execute.before": async (input: any, output: any) => {
      callTermyteHook({
        platform: "opencode",
        event: "tool.execute.before",
        sessionId,
        cwd,
        toolName: input?.tool ?? output?.tool,
        toolInput: output?.args,
        turnId: input?.callID,
      });
    },

    "tool.execute.after": async (input: any, output: any) => {
      callTermyteHook({
        platform: "opencode",
        event: "tool.execute.after",
        sessionId,
        cwd,
        toolName: input?.tool ?? output?.tool,
        toolInput: output?.args,
        toolResponse: output?.result ?? output?.output,
        commandExitCode: output?.exitCode,
        turnId: input?.callID,
      });
    },

    "command.executed": async (input: any, output: any) => {
      callTermyteHook({
        platform: "opencode",
        event: "command.executed",
        sessionId,
        cwd,
        command: input?.command ?? output?.command,
        commandExitCode: output?.exitCode,
      });
    },

    "file.edited": async (input: any) => {
      callTermyteHook({
        platform: "opencode",
        event: "file.edited",
        sessionId,
        cwd,
        filePath: input?.filePath ?? input?.path,
      });
    },
  };
};
